routes:
  - name: Index
    path: /index
    controller: main::index

  - name: Name
    path: /:name
    controller: main::user

  # /download/(.*) - is subpath of /(.*)
  # So we put it in early.
  - name: StaticDownload
    path: /download/(.*)
    static: ./public
    download: true

  - name: Static
    path: /(.*)
    static: ./public
