# yaml-language-server: $schema=https://raw.githubusercontent.com/avil13/avil13-koa-router/master/packages/koa-router/src/avil13-koa-router-json-schema/schema.json

routes:
  - name: Index
    path: /index
    controller: main::index

  - name: Name
    path: /:name
    controller: main::user

  # /download/(.*) - is subpath of /(.*)
  # So we put it in early.
  - name: StaticDownload
    path: /download/(.*)
    static: ./public
    download: true

  - name: Static
    path: /(.*)
    static: ./public
